VaRt-io/V-aRt

- config/default.json
- package-lock.json
- package.json
- public/upload.html
- src/app.js
User stories: As a user, I can upload a file and fetch the URL to my files.
Implementation: Implemented a route for uploading a file to S3 and getting a list of URLs of all my uploaded files.
> S3 image service

- public/canvas.html
- src/app.js
User story: A user can draw on a canvas, save the drawing, upload it to our server, and fetch their drawing later.
Implementation: @alexpress4 created a static canvas with the ability for a user to save the canvas on a button click. I wrote a HTTP post request to our API endpoint with the image saved as a dataURI for the server to upload to S3. The post request function is invoked upon the button click.
> Static canvas

- public/index.html
- public/vr.html
User story: A user can see a drawing they uploaded in VR.
Implementation: Added a VR page using A-frame. Cube renders the user's drawing.
> added VR demo

- package.json
- src/app.js
User story: A user can save a file with a specified galleryid, name, and position. They can also filter images by galleryid.
Implementation: Revised the images route to filter for the query param.
> S3 object tagging

- public/dist/drawingboard.js
User story: A user can upload their canvas image.
Implementation: Refactored the XHR upload request to fetch API.
> refactored upload request implementing xhr to fetch api

- public/dist/drawingboard.js
- src/app.js
- src/services/images/images.class.js
- src/services/images/images.filters.js
- src/services/images/images.hooks.js
- src/services/images/images.service.js
- src/services/index.js
User story: As a user, I can upload an image and see an uploaded image later.
Implementation: Refactored the image service endpoints ('/s3/images & /s3/images/new') from app.js to the services directory.
> Image service refactor

- .gitignore
- config/default.json
- package-lock.json
- src/services/galleries/galleries.service.js
- src/services/users/users.service.js
User story: As a user, I can do a CRUD method on a users or galleries.
Implemented: Added an 'api' prefix to the users and galleries endpoints.
> changes route prefix to /api

- client/components/artists-all.js
- client/components/galleries-all.js
- client/store/galleries.js
- client/store/image.js
- client/store/users.js
changes to related thunks and minor changes to all galleries
> all artists rendering

- client/components/index.js
- client/components/main.js
- client/components/singlePainting.js
- client/store/index.js
- client/store/paintings.js
- public/dist/drawingboard.js
also added spaces being converted to underscores in URL names
> single painting component

- .circleci/config.yml
- src/services/galleries/galleries.hooks.js
- test/services/images.test.js
User story: As a user, I can expected working code.
Implementation: Revised config.yml, fixed test seeding for users, and removed logs from gallery hooks.
> revised config, fixed test seeding, and removed logs from gallery hooks

- client/components/artists-single.js
- client/components/navbar.js
- client/index.scss
- client/store/currentUser.js
User story: As an artist, I can access a dashboard where I can modify my profile and galleries and create a new gallery when I'm logged on.
Implementation: Added conditional rendering to the artist-single page so it renders the dashboard UI elements while logged on. When user is signing in, they are routed to their artist page (which which render the dashboard controls since they will be authenticated at that point).
> Artist dashboard

- client/components/artists-single.js
- client/components/navbar.js
- client/index.scss
- client/store/currentUser.js
- package-lock.json
- package.json
User story: As a user, I can expect my sensitive information is not needlessly saved/utilized.
Implementation: Decoded jwt token to get user information (the userId) instead of setting and getting email to localstorage.
> Jwt decoder

- client/components/gallery-create.js
- client/store/galleries.js
- src/models/galleries.model.js
User story: As a user, I can create a new gallery and make sure it belongs to me.
Implementation: Passed user id from redux state to the handler function in the create gallery component.
> fixed create new gallery bug

- client/components/artists-single.js
- client/components/signup.js
- client/store/currentUser.js
- client/store/users.js
User story: As a new user, I can signup, get logged in automatically, and be routed to my artist dashboard.
Implementation: Dispatched the attemptAuth thunk after posting the user and routing the user to his page.
> Signup bug patch

- client/components/artists-all.js
- client/components/artists-single.js
- client/components/galleries-all.js
- client/components/gallery-edit.js
User story: As a user, I can view a single artist's page both by typing the page url directly in the address bar and by navigating to it within the app.
Implementation: Initialized local state with data from redux state  and created a componentWillReceive props lifecycle method that will set the set state when the global state 
(redux) changes.
> Single artist dashboard edit

- client/components/gallery-single.js
- package-lock.json
Patched env variable in gallery-single
> patched env variable in gallery-single

- client/components/VRArtistHub.js
- client/components/VRDesert.js
- client/components/VRNightScene.js
- client/components/VRStarry.js
User story: As a user, I can stare at a gallery, exit, or back to artist box and it will let me now it is working and it will teleport me there if I stare long enough.
Implementation: Added fuse with fuse timeout on the cursor component and added animation.
> added gaze based click with animation

- package.json
User story: As a user, I can access the deployed app.
Implementation: Added Tom's deploy script for deploying React apps
> added deploy script

- .circleci/config.yml
- src/authentication.js
- src/new-seed.js
- src/sequelize.js
> removed newseed and logging in sequelize.js file

- src/services/images/images.service.js
- src/services/paintings/paintings.hooks.js
- test/services/images.test.js
User story: As a developer, my code will be automatically pushed to a CI server when making a PR which will let me/team know whether that code should be merged.
Implementation: Fixed test environment, removed logs, and added proper test database cleanup code.
> Circleci config
